# -*- coding: utf-8 -*-
"""resumes.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/187M-F7tjZqppj1WPStV54QVx2BNDSsrJ
"""

#!pip install streamlit
#!pip install pdfplumber
#!pip install python-docx

import streamlit as st
import pickle
import pandas as pd
import pdfplumber
import docx
import re

# ======================================
# Load trained model and encoder
# ======================================
# model = pickle.load(open("resume_classifier.pkl", "rb"))
model = pickle.load(open("resume_classifier.pkl", "rb"))
label_encoder = pickle.load(open("label_encoder.pkl", "rb"))

# ======================================
# Text Extraction
# ======================================
def extract_text_from_pdf(file):
    text = ""
    with pdfplumber.open(file) as pdf:
        for page in pdf.pages:
            text += page.extract_text() or ""
    return text

def extract_text_from_docx(file):
    document = docx.Document(file)
    return "\n".join([para.text for para in document.paragraphs])

# ======================================
# Skill & Experience Extraction
# ======================================
skill_list = [
    "python", "java", "sql", "machine learning",
    "deep learning", "excel", "finance",
    "analysis", "power bi", "tableau"
]

def extract_skills(text):
    text_lower = text.lower()
    found_skills = [skill for skill in skill_list if skill in text_lower]
    return ", ".join(found_skills) if found_skills else "Not Found"

def extract_experience(text):
    exp_pattern = re.findall(r"(\d+)\+?\s*(years|yrs)", text.lower())
    if exp_pattern:
        return exp_pattern[0][0] + " Years"
    return "Not Mentioned"

# ======================================
# Feature Engineering (same as training)
# ======================================
def create_features(text):
    resume_length = len(text.split())

    noun_count = len(re.findall(r"\b[A-Z][a-z]+\b", text))

    verb_count = len(re.findall(
        r"\b(is|are|was|were|worked|developed|managed|led|created|built)\b",
        text.lower()
    ))

    skills_text = text.lower()
    skill_count = sum(skills_text.count(skill) for skill in skill_list)

    return pd.DataFrame([{
        "nv_text": text,
        "resume_length": resume_length,
        "noun_count": noun_count,
        "verb_count": verb_count,
        "skills": skills_text,
        "skill_count": skill_count
    }])

# ======================================
# Streamlit UI
# ======================================
st.set_page_config(page_title="Automated Resume Classification")

st.title("📄 Automated Resume Classification System")
st.write("Upload multiple resumes (PDF or DOCX) for classification.")

uploaded_files = st.file_uploader(
    "Upload Resumes",
    type=["pdf", "docx"],
    accept_multiple_files=True
)

# ======================================
# Prediction Logic
# ======================================
if uploaded_files:

    results = []

    for uploaded_file in uploaded_files:

        # Extract text
        if uploaded_file.type == "application/pdf":
            text = extract_text_from_pdf(uploaded_file)
        else:
            text = extract_text_from_docx(uploaded_file)

        if text.strip() == "":
            continue

        # Create features for model
        input_df = create_features(text)

        # Predict
        prediction = model.predict(input_df)
        predicted_category = label_encoder.inverse_transform(prediction)[0]

        # Extract extra info
        experience = extract_experience(text)
        skills = extract_skills(text)

        results.append({
            "File Name": uploaded_file.name,
            "Predicted Category": predicted_category,
            "Experience": experience,
            "Skills": skills
        })

    if results:
        results_df = pd.DataFrame(results)
        st.success("✅ Classification Completed")
        st.dataframe(results_df)
    else:
        st.error("No valid resumes found.")